name: a

on: push

    # schedule:
    #  - cron: "0 1 * * *"

jobs:
    job1:
        runs-on: windows-2025
        steps:
         - uses: action
    
         - run: python --version
         - run: python ./a.py
